apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-1tfp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-1tfp@sha256:45074a00359fb43ec200b95ded795df68d26e9a1e0d99cb4b58557f6c32d2f72
        name: my-python
        resources: {}
status: {}
