apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-rag4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-rag4@sha256:cc45c9d2bf36de9367d515f0a1e407daf93def526e88d36e2ee497d58d703b2b
        name: my-nodejs
        resources: {}
status: {}
